### ISSUE TITLE
Check E190 Constant Throttle Regression

### ISSUE THREAD

**Issue by planes** [suavecode/SUAVE#101]
Tarik,
Could you check the results for the E190 Regression? It runs okay and the results don't seem outlandish.

Thanks!

**Comment by tarikorra** [comment]
sure. 
could you please tell me in which folder of which branch is the script you are refering to?

**Comment by aerialhedgehog** [comment]
develop branch --
scripts/regression/test_Embraer_E190_constThr
- trent

thanks tarik!

**Comment by tarikorra** [comment]
I have not been able to check it due to the OrderedBunch error below:  (I will try later in other pc)

Traceback (most recent call last):
  File "C:\_Tarik\03 DT\00 GEN2\90 Software\SUAVE_develop\scripts\regression\test_mission_Embraer_E190_constThr.py", line 1021, in <module>
    main()
  File "C:\_Tarik\03 DT\00 GEN2\90 Software\SUAVE_develop\scripts\regression\test_mission_Embraer_E190_constThr.py", line 54, in main
    old_results = load_results()
  File "C:\_Tarik\03 DT\00 GEN2\90 Software\SUAVE_develop\scripts\regression\test_mission_Embraer_E190_constThr.py", line 1013, in load_results
    return SUAVE.Input_Output.SUAVE.load('results_mission_E190_constThr.res')
  File "c:\_tarik\03 dt\00 gen2\90 software\suave_develop\trunk\SUAVE\Input_Output\SUAVE\load.py", line 21, in load
    data = vypy_load(filename,file_format='pickle')
  File "c:\_tarik\03 dt\00 gen2\90 software\suave_develop\trunk\SUAVE\Plugins\VyPy\data\input_output.py", line 73, in load_data
    input_data = load_pickle(file_name)
  File "c:\_tarik\03 dt\00 gen2\90 software\suave_develop\trunk\SUAVE\Plugins\VyPy\data\input_output.py", line 194, in load_pickle
    data_dict[key] = pickle.load(pkl_file)
ImportError: No module named OrderedBunch

**Comment by aerialhedgehog** [comment]
i'm really at a loss with this one tarik =(
i'll send you a seperate email with some more debuging ideas...

**Comment by planes** [comment]
Regressions are working fine now.
