### ISSUE TITLE
propeller_design.py not working because NACA.txt files missing

### ISSUE THREAD

**Issue by spinjet** [suavecode/SUAVE#402]
Hello, I was testing the new `internal_combustion_propeller_cs ` network using the [ICE_CS_test.py](https://github.com/suavecode/SUAVE/blob/develop/regression/scripts/internal_combustion_propeller/ICE_CS_Test.py) script.

The error is as follows:

```No airfoils specified for propeller or rotor airfoil specified. 
Defaulting to NACA 4412 airfoils that will provide conservative estimates.
Traceback (most recent call last):

  File "C:\Users\...\SUAVE23\SUAVE\regression\scripts\internal_combustion_propeller\ICE_CS_Test.py", line 234, in <module>
    main()

  File "C:\Users\...\SUAVE23\SUAVE\regression\scripts\internal_combustion_propeller\ICE_CS_Test.py", line 39, in main
    vehicle = ICE_CS(vehicle)

  File "C:\Users\...\SUAVE23\SUAVE\regression\scripts\internal_combustion_propeller\ICE_CS_Test.py", line 103, in ICE_CS
    prop                     = propeller_design(prop)

  File "C:\Users\...\Anaconda3\envs\suave23\lib\site-packages\suave-2.3.0-py3.8.egg\SUAVE\Methods\Propulsion\propeller_design.py", line 146, in propeller_design
    airfoil_polars  = compute_airfoil_polars(a_geo, a_pol)

  File "C:\Users\...\Anaconda3\envs\suave23\lib\site-packages\suave-2.3.0-py3.8.egg\SUAVE\Methods\Geometry\Two_Dimensional\Cross_Section\Airfoil\compute_airfoil_polars.py", line 59, in compute_airfoil_polars
    airfoil_data = import_airfoil_geometry(a_geo)

  File "C:\Users\...\Anaconda3\envs\suave23\lib\site-packages\suave-2.3.0-py3.8.egg\SUAVE\Methods\Geometry\Two_Dimensional\Cross_Section\Airfoil\import_airfoil_geometry.py", line 64, in import_airfoil_geometry
    f = open(airfoil_geometry_files[i])

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/.../Anaconda3/envs/suave23/lib/site-packages/suave-2.3.0-py3.8.egg/regression\\scripts\\Vehicles\\NACA_4412.txt' 
```

I personally fixed it by removing `trunk\` from [here](https://github.com/suavecode/SUAVE/blob/65260d4f0bf7c72dd1746b0d5986d8c3283107f0/trunk/SUAVE/Methods/Propulsion/propeller_design.py#L125), and copying the `regression` folder in the root folder of the SUAVE library.

You should provide these files installed withing the `setup.py` script.

**Comment by SeungKil-Paek** [comment]
First, uninstall suave.

> pip uninstall suave

Then, install suave with editable option.

> cd trunk
> pip install -e .  <--- See there is a dot "."
