### ISSUE TITLE
'AttributeError: Conditions' object has no attribute 'propeller_motor_torque'

### ISSUE THREAD

**Issue by BBFlyer1** [suavecode/SUAVE#479]
The following Traceback is from Windows 10 using Anaconda Spyder 5.05 with python 3.8 and a local copy of the tut_solar_uav.py file.   The only local change to tut_solar_uav.py before the error was to replace all propulsors with networks to fix the error "propulsors not found" .

runfile('E:/Users/Bob/Documents/python/suave/Solar-UAV/tut_solar_uav.py', wdir='E:/Users/Bob/Documents/python/suave/Solar-UAV')

Designing propeller

Defaulting to scaled DAE51
Traceback (most recent call last):

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Core\Data.py", line 61, in __getattribute__
    return dictgetitem(self,k)

KeyError: 'propeller_motor_torque'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\Users\Bob\Documents\python\suave\Solar-UAV\tut_solar_uav.py", line 474, in <module>
    main()

  File "E:\Users\Bob\Documents\python\suave\Solar-UAV\tut_solar_uav.py", line 38, in main
    results = mission.evaluate()

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Mission\Segments\Segment.py", line 199, in evaluate
    self.process(self)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Process.py", line 67, in evaluate
    result = step(*args,**kwarg)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Methods\Missions\Segments\Common\Sub_Segments.py", line 131, in sequential_sub_segments
    sub_segment.evaluate()

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Mission\Segments\Segment.py", line 199, in evaluate
    self.process(self)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Process.py", line 65, in evaluate
    result = step.evaluate(*args,**kwarg)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Process.py", line 67, in evaluate
    result = step(*args,**kwarg)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Methods\Missions\Segments\converge_root.py", line 50, in converge_root
    unknowns,infodict,ier,msg = root_finder( iterate,

  File "E:\Users\Bob\anaconda3\lib\site-packages\scipy\optimize\minpack.py", line 160, in fsolve
    res = _root_hybr(func, x0, args, jac=fprime, **options)

  File "E:\Users\Bob\anaconda3\lib\site-packages\scipy\optimize\minpack.py", line 226, in _root_hybr
    shape, dtype = _check_func('fsolve', 'func', func, x0, args, n, (n,))

  File "E:\Users\Bob\anaconda3\lib\site-packages\scipy\optimize\minpack.py", line 24, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Methods\Missions\Segments\converge_root.py", line 99, in iterate
    segment.process.iterate(segment)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Process.py", line 65, in evaluate
    result = step.evaluate(*args,**kwarg)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Analyses\Process.py", line 67, in evaluate
    result = step(*args,**kwarg)

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Components\Energy\Networks\Solar.py", line 295, in residuals
    q_motor   = segment.state.conditions.propulsion.propeller_motor_torque

  File "E:\Users\Bob\anaconda3\lib\site-packages\suave-2.4.0-py3.8.egg\SUAVE\Core\Data.py", line 63, in __getattribute__
    return objgetattrib(self,k)

AttributeError: 'Conditions' object has no attribute 'propeller_motor_torque'

**Comment by planes** [comment]
This has been addressed in the latest release #513
