### ISSUE TITLE
_winapi.CreateProcess issue on B737-800 AVL tutorial  (Anaconda)

### ISSUE THREAD

**Issue by rootAmos** [suavecode/SUAVE#520]
Hello, 

Thanks for making this incredible tool!! I think it's the best open source aircraft design framework out there by miles 

I'm trying to run the tut_mission_B737_AVL tutorial, but it seems that when Anaconda tries to create a process to run the AVL file, it throws a file not found error. I'm using a virtual enviroment (Python 3.9) in Anaconda.  The print out is below.

Any idea what could be going wrong? It seems that it's more an issue with anaconda trying to start the process of loading the avl files than something on your end. I also get the same error if I run the file from the command prompt directly. (Note that I'm still using a virtual environment in that case)

Traceback (most recent call last):
  File "D:\shibuya\Tutorials-2.4.0\Tutorials-2.4.0\B737_AVL_Tutorial\tut_mission_B737_AVL.py", line 738, in <module>
    main()
  File "D:\shibuya\Tutorials-2.4.0\Tutorials-2.4.0\B737_AVL_Tutorial\tut_mission_B737_AVL.py", line 36, in main
    analyses.finalize()
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Analyses\Analysis.py", line 271, in finalize
    analysis.finalize(*args,**kwarg)
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Analyses\Analysis.py", line 271, in finalize
    analysis.finalize(*args,**kwarg)
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Analyses\Analysis.py", line 271, in finalize
    analysis.finalize(*args,**kwarg)
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Analyses\Aerodynamics\AVL.py", line 130, in initialize
    self.process.compute.lift.inviscid.initialize(sv,cv)
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Analyses\Aerodynamics\AVL_Inviscid.py", line 130, in initialize
    self.sample_training()
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Analyses\Aerodynamics\AVL_Inviscid.py", line 258, in sample_training
    results =  self.evaluate_conditions(run_conditions, trim_aircraft)
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Analyses\Aerodynamics\AVL_Inviscid.py", line 439, in evaluate_conditions
    results_avl = run_analysis(self)
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Methods\Aerodynamics\AVL\run_analysis.py", line 39, in run_analysis
    call_avl(avl_object)
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\site-packages\suave-2.4.0-py3.9.egg\SUAVE\Methods\Aerodynamics\AVL\run_analysis.py", line 86, in call_avl
    avl_run = subprocess.Popen([avl_call,geometry],stdout=sys.stdout,stderr=sys.stderr,stdin=subprocess.PIPE)
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Alex\Anaconda3\envs\suave\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by rootAmos** [comment]
Looks like I didn't install avl properly - my mistake here
