### ISSUE TITLE
tut_tailsitter.py not working, no compute_airfoil_polars?

### ISSUE THREAD

**Issue by stuartcrobinson** [suavecode/SUAVE#648]
https://github.com/suavecode/Tutorials/blob/master/tut_tailsitter.py#L22

can't find any reference to `compute_airfoil_polars` in the code, aside from an old issue

tut_mission_B737.py works fine for me

after just removing the import for `compute_airfoil_polars` i get this error:

```
~/r/Tutorials (master)> python3 tut_tailsitter.py                                                                                          (base)

Defaulting to scaled DAE51
Traceback (most recent call last):
  File "/Users/stuart/repos/Tutorials/tut_tailsitter.py", line 496, in <module>
    main()
  File "/Users/stuart/repos/Tutorials/tut_tailsitter.py", line 37, in main
    results = mission.evaluate()
              ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Mission/Segments/Segment.py", line 180, in evaluate
    self.process(self)
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 67, in evaluate
    result = step(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Methods/Missions/Segments/Common/Sub_Segments.py", line 137, in sequential_sub_segments
    sub_segment.evaluate()
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Mission/Segments/Segment.py", line 180, in evaluate
    self.process(self)
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 65, in evaluate
    result = step.evaluate(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 67, in evaluate
    result = step(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Methods/Missions/Segments/converge_root.py", line 50, in converge_root
    unknowns,infodict,ier,msg = root_finder( iterate,
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scipy/optimize/_minpack_py.py", line 166, in fsolve
    res = _root_hybr(func, x0, args, jac=fprime, **options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scipy/optimize/_minpack_py.py", line 232, in _root_hybr
    shape, dtype = _check_func('fsolve', 'func', func, x0, args, n, (n,))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/scipy/optimize/_minpack_py.py", line 29, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Methods/Missions/Segments/converge_root.py", line 99, in iterate
    segment.process.iterate(segment)
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 65, in evaluate
    result = step.evaluate(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 67, in evaluate
    result = step(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Methods/Missions/Segments/Common/Aerodynamics.py", line 189, in update_aerodynamics
    results = aerodynamics_model( segment.state )
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Analysis.py", line 155, in __call__
    return self.evaluate(*args,**kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Aerodynamics/Markup.py", line 84, in evaluate
    results = self.process.compute(state,settings,geometry)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 96, in __call__
    return self.evaluate(*args,**kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 65, in evaluate
    result = step.evaluate(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Aerodynamics/Process_Geometry.py", line 75, in evaluate
    result = Process.evaluate(self,state,settings,this_geometry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Analyses/Process.py", line 67, in evaluate
    result = step(*args,**kwarg)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/SUAVE-2.5.2-py3.12.egg/SUAVE/Methods/Aerodynamics/AERODAS/post_stall_coefficients.py", line 87, in post_stall_coefficients
    CL2[con3] = -0.032*(alpha[con3]/Units.deg-92.0) + RCL2*((alpha[con3]-92.*Units.deg)/(51.0*Units.deg))**N2
                        ~~~~~^^^^^^
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```

**Comment by stuartcrobinson** [comment]
nevermind. i was using the wrong version.
